version: '3'

services:
  web:
    container_name: php-pt07
    build: .
    # image: 192.168.1.12:5000/php-pt07
    ports:
      - "8023:80"
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - ./:/var/www/html
  mysql:
    container_name: mysql-pt07
    # image: mysql:8.0.31-debian
    build: ./db/.
    # image: 192.168.1.12:5000/mysql-pt07
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # en cas de voler accedir amb un programa d'administracio com HeidiSQL, descomentem els ports
    # ports:
    #   - "3323:3306"
    # en cas de voler canviar el sql, podem muntar el sql
    # volumes:
    #   - ./pt07-marc-peral.sql:/docker-entrypoint-initdb.d/pt07-marc-peral.sql
    environment:
      # en cas de voler fer servir una contrasenya buida, podem descomentar la seguent linia
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: patata
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
