version: '3'

services:
  web:
    container_name: php-pt07
    build: .
    # image: 192.168.1.12:5000/php-pt07
    expose:
      - 80
    # ports:
    #   - "8023:80"
    stdin_open: true
    tty: true
    volumes:
      - ./:/var/www/html
